language: php
php:
  - '7.2'

before_script:
- pecl install -f mongo:1.6.16
- composer install --prefer-dist --no-interaction
script:
- composer phpstan
#- "./vendor/bin/phpunit"
#after_script:
#- php vendor/bin/coveralls -v
