<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 * This file contains the status of all Mouf global installation processes for packages you have installed.
 * If you are working with a source repository, this file should be commited.
 */
return array (
  0 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Common\\Doctrine\\Annotations\\AnnotationReaderInstaller',
    'package' => 'mouf/utils.common.doctrine-annotations-wrapper',
  ),
  1 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.renderer.twig-extensions',
  ),
  2 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.cache.file-cache',
  ),
  3 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Log\\Psr\\ErrorLogLoggerInstaller',
    'package' => 'mouf/utils.log.psr.errorlog_logger',
  ),
  4 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.cache.apc-cache',
  ),
  5 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.renderer',
  ),
  6 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'install.php',
    'package' => 'mouf/html.utils.weblibrarymanager',
  ),
  7 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'install.php',
    'package' => 'mouf/javascript.jquery.jquery',
  ),
  8 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'install.php',
    'package' => 'mouf/html.utils.bootstrap',
  ),
  9 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.widgets.menu',
  ),
  10 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.session.session-manager',
  ),
  11 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.widgets.messageservice',
  ),
  12 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.template.bootstrap',
  ),
  13 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.i18n.fine',
  ),
  14 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/validatorsInstall.php',
    'package' => 'mouf/utils.common.validators',
  ),
  15 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/splashCommonInstall.php',
    'package' => 'mouf/mvc.splash-common',
  ),
  16 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.cache.no-cache',
  ),
  17 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Constants\\SecretInstaller',
    'package' => 'mouf/utils.constants.secret',
  ),
  18 => 
  array (
    'status' => 'done',
    'type' => 'url',
    'url' => 'splashinstall/',
    'package' => 'mouf/mvc.splash',
  ),
  19 => 
  array (
    'status' => 'done',
    'type' => 'url',
    'url' => 'splashinstall/writeHtAccess',
    'package' => 'mouf/mvc.splash',
  ),
  20 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'install.php',
    'package' => 'mouf/modules.google-analytics',
  ),
  21 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.log.errorlog_logger',
  ),
);