<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 * This file contains the status of all Mouf local installation processes for packages you have installed.
 * If you are working with a source repository, this file should NOT be commited.
 */
return array (
);