---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "web"
  labels:
    app: "web"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "web"
  template:
    metadata:
      labels:
        app: "web"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: "web"
        image: "thecodingmachine/packanalyst:master"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: config
            optional: false
        volumeMounts:
          - name: files-data
            mountPath: /var/downloads
        resources:
          requests:
            memory: "1G"
            cpu: "1"
          limits:
            memory: "8G"
            cpu: "4"
      volumes:
      - name: files-data
        persistentVolumeClaim:
          claimName: files-claim
---
apiVersion: v1
kind: ConfigMap
data:
  # The host name for the Elastic Search server
  ELASTICSEARCH_HOST: "elasticsearch"
  # The default port to connect to Elastic Search server
  ELASTICSEARCH_PORT: "9200"
  # A random string. It should be different for any application deployed.
  SECRET: "HLxRssObAZpJdFYfHJpT"
  # The download directory
  DOWNLOAD_DIR: "/var/downloads"
  # Connection string to MongoDB
  MONGODB_CONNECTIONSTRING: "mongodb://mongo:27017"
  # Your Google Analytics key. Leave empty if you want to disable Google Analytics tracking. Don't have a key for your website? Get one here: http://www.google.com/analytics/
  GOOGLE_ANALYTICS_KEY: "UA-25804465-2"
  # The base domain name to track (if you are tracking sub-domains). In the form: '.example.com'. Keep this empty if you don't track subdomains.
  GOOGLE_ANALYTICS_DOMAIN_NAME: ""
  # Set to true to enable debug/development mode.
  DEBUG: "true"
  # Disable Mouf UI
  MOUF_UI: "0"
metadata:
  name: config
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: "web"
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-claim
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 150Gi
---
