name: Build Docker Image

on:
  push:
    branches:
      - master
      - docker # for testing purpose

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --tag thecodingmachine/packanalyst:latest
